# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dabb54c6b1011c88ca678ebc4cfeef726ba27c8f4346f040966b7520e4c7be9c3ba3b444097acf9ac75dcecc4708a42ab04a0152099b05215e61c018a1dd4150

test:
  secret_key_base: cd9b1423bdbebb8958a1927b2442caee1015938ccda96a385e2111d1ad6a711aac5d37d17d09e4dde0fdc5716329b6a7bc783ff593c0ff03b5de4da8e7c4b022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
